# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fish.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FishWindow(object):
    def setupUi(self, FishWindow):
        FishWindow.setObjectName("FishWindow")
        FishWindow.resize(326, 627)
        FishWindow.setMinimumSize(QtCore.QSize(326, 627))
        FishWindow.setMaximumSize(QtCore.QSize(326, 627))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("image/QQ1.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        FishWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(FishWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 331, 141))
        self.frame.setStyleSheet("background-color:#00AAAA;\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(120, 30, 70, 65))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setStyleSheet("background-image:url(image/qq.jpeg)")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(120, 100, 91, 21))
        self.label.setStyleSheet("background-color: #00AAAA;\n"
"color: rgb(255, 255, 255);\n"
"")
        self.label.setObjectName("label")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setGeometry(QtCore.QRect(294, 0, 31, 23))
        self.pushButton_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 85, 255);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame)
        self.pushButton_4.setGeometry(QtCore.QRect(260, 0, 31, 23))
        self.pushButton_4.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 85, 255);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(0, 140, 326, 35))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.pushButton = QtWidgets.QPushButton(self.frame_3)
        self.pushButton.setGeometry(QtCore.QRect(0, 2, 163, 35))
        self.pushButton.setStyleSheet("background-color: rgb(255, 239, 239);")
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_2.setGeometry(QtCore.QRect(160, 2, 171, 35))
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 248, 248);")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("image/wechat.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setObjectName("pushButton_2")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(0, 171, 331, 451))
        self.listWidget.setIconSize(QtCore.QSize(45, 45))
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("image/classmate.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon2)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("image/learn.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon3)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("image/partjob.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon4)
        self.listWidget.addItem(item)
        self.treeWidget = QtWidgets.QTreeWidget(self.centralwidget)
        self.treeWidget.setGeometry(QtCore.QRect(-3, 171, 331, 441))
        self.treeWidget.setStyleSheet("background: #fff;\n"
"border-color: #fff;\n"
"padding-left: 10px;")
        self.treeWidget.setAutoScrollMargin(10)
        self.treeWidget.setIconSize(QtCore.QSize(40, 40))
        self.treeWidget.setAutoExpandDelay(-1)
        self.treeWidget.setIndentation(6)
        self.treeWidget.setColumnCount(1)
        self.treeWidget.setObjectName("treeWidget")
        font = QtGui.QFont()
        font.setPointSize(15)
        self.treeWidget.headerItem().setFont(0, font)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0.setToolTip(0, "")
        font = QtGui.QFont()
        font.setPointSize(12)
        item_0.setFont(0, font)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setPointSize(11)
        item_1.setFont(0, font)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("image/chatbk.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item_1.setIcon(0, icon5)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setPointSize(11)
        item_1.setFont(0, font)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("image/qq.jpeg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item_1.setIcon(0, icon6)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setPointSize(11)
        item_1.setFont(0, font)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("image/loginbk.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item_1.setIcon(0, icon7)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        item_0.setFont(0, font)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setPointSize(11)
        item_1.setFont(0, font)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("image/qqchatbk.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item_1.setIcon(0, icon8)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        item_0.setFont(0, font)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setPointSize(11)
        item_1.setFont(0, font)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("image/qqlogin.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item_1.setIcon(0, icon9)
        self.listWidget.raise_()
        self.treeWidget.raise_()
        self.frame.raise_()
        self.frame_3.raise_()
        FishWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(FishWindow)
        self.statusbar.setObjectName("statusbar")
        FishWindow.setStatusBar(self.statusbar)

        self.retranslateUi(FishWindow)
        self.pushButton_3.clicked.connect(FishWindow.close)
        self.pushButton.clicked.connect(self.listWidget.hide)
        self.pushButton_2.clicked.connect(self.listWidget.show)
        self.pushButton.clicked.connect(self.treeWidget.show)
        self.pushButton_2.clicked.connect(self.treeWidget.hide)
        self.pushButton_4.clicked.connect(FishWindow.showMinimized)
        QtCore.QMetaObject.connectSlotsByName(FishWindow)

    def retranslateUi(self, FishWindow):
        _translate = QtCore.QCoreApplication.translate
        FishWindow.setWindowTitle(_translate("FishWindow", "鱼聊"))
        self.label.setText(_translate("FishWindow", "欢迎:鱼聊小王"))
        self.pushButton_3.setText(_translate("FishWindow", "关闭"))
        self.pushButton_4.setText(_translate("FishWindow", "隐藏"))
        self.pushButton.setText(_translate("FishWindow", "好友"))
        self.pushButton_2.setText(_translate("FishWindow", "群聊"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("FishWindow", "同学群"))
        item = self.listWidget.item(1)
        item.setText(_translate("FishWindow", "学习群"))
        item = self.listWidget.item(2)
        item.setText(_translate("FishWindow", "兼职群"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.treeWidget.headerItem().setText(0, _translate("FishWindow", "好友"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("FishWindow", "朋友"))
        self.treeWidget.topLevelItem(0).child(0).setText(0, _translate("FishWindow", "小王"))
        self.treeWidget.topLevelItem(0).child(1).setText(0, _translate("FishWindow", "小李"))
        self.treeWidget.topLevelItem(0).child(2).setText(0, _translate("FishWindow", "小马"))
        self.treeWidget.topLevelItem(1).setText(0, _translate("FishWindow", "同学"))
        self.treeWidget.topLevelItem(1).child(0).setText(0, _translate("FishWindow", "小程"))
        self.treeWidget.topLevelItem(2).setText(0, _translate("FishWindow", "好友"))
        self.treeWidget.topLevelItem(2).child(0).setText(0, _translate("FishWindow", "小伟"))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
